### ISSUE TITLE
Candles with strength effect causing client side crash - 1.19.2

### ISSUE THREAD

**Issue by Dweblenod** [JoeFoxe/Hexerei-1.18#101]
Recreating bug:
1. Loaded up a modpack containing Hexerei 0.3.3.1
2. Fill a cauldron with strength potion
3. Started dipping a red hexerei candle and let the process complete on its own
4. Took the candle out, placed it on the ground
5. Upon lighting the candle, the game crashes the client of any player within render distance

A red candle was tested with instant health, which did not cause a crash. Have not tested any potion types beyond those two.

First few pieces of crash log
```
Description: Ticking block entity

java.lang.ClassCastException: class net.minecraft.core.particles.ParticleTypes$1 cannot be cast to class net.minecraft.core.particles.ParticleOptions (net.minecraft.core.particles.ParticleTypes$1 and net.minecraft.core.particles.ParticleOptions are in module minecraft@1.19.2 of loader 'TRANSFORMER' @2b6fb197)
	at net.joefoxe.hexerei.data.candle.PotionCandleEffect.tick(PotionCandleEffect.java:59) ~[hexerei-0.3.3.1.jar%23289!/:0.3.3.1] {re:classloading}
	at net.joefoxe.hexerei.tileentity.CandleTile.tick(CandleTile.java:395) ~[hexerei-0.3.3.1.jar%23289!/:0.3.3.1] {re:mixin,re:computing_frames,re:classloading}
at net.joefoxe.hexerei.block.custom.Candle.lambda$getTicker$4(Candle.java:667) ~[hexerei-0.3.3.1.jar%23289!/:0.3.3.1] {re:mixin,re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[client-1.19.2-20220805.130853-srg.jar%23349!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[client-1.19.2-20220805.130853-srg.jar%23349!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[client-1.19.2-20220805.130853-srg.jar%23349!/:?]
```

**Comment by JacksonTrexler** [comment]
This occurred for my friend who was using a standard Hexerei candle. Has anyone found a workaround for the time being?

Error: java.lang.ClassCastException: class net.minecraft.core.particles.ParticleTypes$1 cannot be cast to class net.minecraft.core.particles.ParticleOptions (net.minecraft.core.particles.ParticleTypes$1 and net.minecraft.core.particles.ParticleOptions are in module minecraft@1.19.2 of loader 'TRANSFORMER' @7ed7ae)

**Comment by deadkex** [comment]
For example for Enigmatica9Expert you can run this command: /execute in twilightforest:twilight_forest run fill x1 y1 z1 x2 y2 z2 minecraft:dirt replace hexerei:candle
