### ISSUE TITLE
Something something slab flower crash?

### ISSUE THREAD

**Issue by nivthefox** [JoeFoxe/Hexerei-1.18#31]
I'm a little unclear what's actually going on here, but here's the relevant data from a crash that's happened twice tonight on my server:

````net.minecraft.ReportedException: Exception ticking world
at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:872) ~[server-1.18.1-20211210.034407-srg.jar%23108!/:?]
at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%23108!/:?]
at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%23108!/:?]
at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%23108!/:?]
at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23108!/:?]
at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalArgumentException: Cannot set property IntegerProperty{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3]} as it does not exist in Block{hexerei:mahogany_slab}
at net.minecraft.world.level.block.state.StateHolder.m_61124_(StateHolder.java:117) ~[server-1.18.1-20211210.034407-srg.jar%23108!/:?]
at net.joefoxe.hexerei.block.custom.PickableDoubleFlower.m_7455_(PickableDoubleFlower.java:118) ~[hexerei-0.1.16.jar%2375!/:0.1.16]
at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60735_(BlockBehaviour.java:679) ~[server-1.18.1-20211210.034407-srg.jar%23108!/:?]
at net.minecraft.server.level.ServerLevel.m_8714_(ServerLevel.java:437) ~[server-1.18.1-20211210.034407-srg.jar%23108!/:?]
at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:359) ~[server-1.18.1-20211210.034407-srg.jar%23108!/:?]
at net.minecraft.server.level.ServerChunkCache.m_142483_(ServerChunkCache.java:311) ~[server-1.18.1-20211210.034407-srg.jar%23108!/:?]
at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:278) ~[server-1.18.1-20211210.034407-srg.jar%23108!/:?]
at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[server-1.18.1-20211210.034407-srg.jar%23108!/:?]
... 5 more

```

One of the players on the server is running through a Witch Village and we're pretty sure it's related, somehow.

**Comment by JoeFoxe** [comment]
This will 100% be fixed next patch, I thought I fixed it but I missed one case which still causes crashes, but now it should cover all cases and never crash from this :)

**Comment by Darkfiend009** [comment]
Unfortunately, it appears another one may have been missed:

Crash Report: https://pastebin.com/RFHawV8K

Hexerei: 0.1.19
Minecraft 1.18.2
Forge: 40.1.19
