### ISSUE TITLE
Hexeri Crashing Servers Due to Chunk Loak

### ISSUE THREAD

**Issue by Zelioth** [JoeFoxe/Hexerei-1.18#75]
Minecraft 1.19.2
Forge 43.1.57
Hexeri : Latest Version

Hexerei appears to be loading chunks in "onchunkunloaded" which is causing an instant server crash. 

[crash-2022-11-27_21.06.19-server.txt](https://github.com/JoeFoxe/Hexerei-1.18/files/10099269/crash-2022-11-27_21.06.19-server.txt)
[Console Crash information.txt](https://github.com/JoeFoxe/Hexerei-1.18/files/10099270/Console.Crash.information.txt)

**Comment by UdoMorgenstern** [comment]
seems to be related to https://github.com/JoeFoxe/Hexerei-1.18/issues/69

`at net.joefoxe.hexerei.tileentity.ModChestBlockEntity.sync(ModChestBlockEntity.java:157) ~[hexerei-0.2.5.jar%23324!/:0.2.5] {re:classloading}
	at net.joefoxe.hexerei.tileentity.ModChestBlockEntity.onChunkUnloaded(ModChestBlockEntity.java:151) ~[hexerei-0.2.5.jar%23324!/:0.2.5] {re:classloading}`

**Comment by nathan-lewis-1** [comment]
I'm also having this issue with my server.

at net.joefoxe.hexerei.tileentity.ModChestBlockEntity.sync(ModChestBlockEntity.java:157) ~[hexerei-0.2.5.jar%23556!/:0.2.5] {re:classloading}
at net.joefoxe.hexerei.tileentity.ModChestBlockEntity.onChunkUnloaded(ModChestBlockEntity.java:151) ~[hexerei-0.2.5.jar%23556!/:0.2.5] {re:classloading}
